---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhooks-lb
data:
  haproxy.cfg: |
    frontend web
        bind *:80
        mode http
        acl channel path_reg ^\/[0-9a-f]{7}
        default_backend webapp
        use_backend api if channel
        timeout client 30s

    backend api
        mode http
        server node webhooks-api:8080
        timeout connect 5s
        timeout server 30s

    backend webapp
        mode http
        server node webhooks-webapp:3000
        timeout connect 5s
        timeout server 30s
