---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-<ENV>-api
spec:
  selector:
    matchLabels:
      app: webhooks-<ENV>-api
  template:
    metadata:
      labels:
        app: webhooks-<ENV>-api
    spec:
      containers:
        - name: api
          image: "myhro/webhooks:<VERSION>"
          command:
            - /app/api
          env:
            - name: GIN_MODE
              value: release
            - name: REDIS_ADDR
              value: "webhooks-<ENV>-redis:6379"
          ports:
            - containerPort: 8080
