---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webhooks-<ENV>-redis
spec:
  selector:
    matchLabels:
      app: webhooks-<ENV>-redis
  serviceName: webhooks-<ENV>-redis
  template:
    metadata:
      labels:
        app: webhooks-<ENV>-redis
    spec:
      containers:
        - name: redis
          image: redis:4-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: webhooks-<ENV>-redis
spec:
  selector:
    app: webhooks-<ENV>-redis
  ports:
    - port: 6379
      targetPort: 6379
