compatibility_date = "2021-12-26"
name = "webhooks-api"
type = "javascript"
workers_dev = true

[build]

[build.upload]
dir = "src/"
format = "modules"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[durable_objects]

[[durable_objects.bindings]]
name = "listener"
class_name = "Listener"

[env]

[env.staging]

[env.staging.durable_objects]

[[env.staging.durable_objects.bindings]]
name = "listener"
class_name = "Listener"

[env.production]

[env.production.durable_objects]

[[env.production.durable_objects.bindings]]
name = "listener"
class_name = "Listener"
