---
name: WebApp
on:
  push:
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Check
        run: |
          cd webapp/
          make deps
          make check
          make lint
          make tsc
  build:
    needs: check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Build
        run: |
          cd webapp/
          make deps
          make build
