---
name: Worker
on:
  push:
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Lint
        run: |
          cd worker/
          make deps
          make lint
  deploy:
    needs: check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd worker/
          make deps
          make deploy
  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ENV: production
        run: |
          cd worker/
          make deps
          make deploy
