---
name: Worker
on:
  push:
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Lint
        run: |
          cd worker/
          make deps
          make lint
